Uses `TF_BUILD` in vendors.json
watson/ci-info pull request #116
Opened 2023-10-02 21:02 UTC by jessehouwing

Alternative to https://github.com/watson/ci-info/pull/115

2023-10-03 02:04 UTC, jrdodds commented
From a comment in another PR, it seems this is the more correct approach (versus #115).

2023-10-03 13:28 UTC, sibiraj-s commented
Thank you @jessehouwing . Can you add tests as well? here https://github.com/watson/ci-info/blob/master/test.js

2023-10-03 13:34 UTC, sibiraj-s requested changes
Changes Looks good. 

Will merge and publish by tomorrow once tests are fixed

2023-10-03 19:20 UTC, jrdodds commented
You may only need to identify existing tests. Tests were added with PR #23 for "is/is not a pull request".

2023-10-03 19:28 UTC, jrdodds commented
It seems like the setup and teardown of the environment variables in the 'Azure Pipelines - PR' and 'Azure Pipelines - Not PR' tests needs to be updated. Looks straight-forward.

2023-10-03 21:50 UTC, jessehouwing commented
Also tested in actual Azure Pipelines Build and PR:

```
Starting: CmdLine
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.212.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/cdbbdb6f-d565-4658-a9db-477a3e230853.sh
Cloning into 'ci-info'...
Switched to a new branch 'patch-2'
branch 'patch-2' set up to track 'origin/patch-2'.

> ci-info@3.8.0 prepare
> husky install

husky - Git hooks installed

added 259 packages, and audited 260 packages in 12s

114 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
The name of the CI server is: Azure Pipelines
Is this a pull request?: true
Finishing: CmdLine
```

2023-10-04 04:23 UTC, sibiraj-s approved these changes
Great. Thanks 🎉

2023-10-04 04:47 UTC, merged

2023-10-04 04:57 UTC, sibiraj-s commented
Published in v3.9.0